workspace = { members = ["run_day_macro"] }
[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
quote = "1.0.35"
reqwest = { version = "0.11.25", features = ["blocking"] }
text_io = "0.1.12"
run_day_macro = { path = "./run_day_macro/" }
